// Code generated by "stringer -type=Apparatus apparatus.go"; DO NOT EDIT.

package domain

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Floor-0]
	_ = x[PommelHorse-1]
	_ = x[StillRings-2]
	_ = x[Vault-3]
	_ = x[ParallelBars-4]
	_ = x[HorizontalBar-5]
	_ = x[BalanceBeam-6]
	_ = x[UnevenBars-7]
}

const _Apparatus_name = "FloorPommelHorseStillRingsVaultParallelBarsHorizontalBarBalanceBeamUnevenBars"

var _Apparatus_index = [...]uint8{0, 5, 16, 26, 31, 43, 56, 67, 77}

func (i Apparatus) String() string {
	if i < 0 || i >= Apparatus(len(_Apparatus_index)-1) {
		return "Apparatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Apparatus_name[_Apparatus_index[i]:_Apparatus_index[i+1]]
}
